language: python
matrix:
  include:
    - name: "Python 3.8"
      python: "3.8"
    - name: "Python 3.7"
      python: "3.7"
    - name: "Python 3.6"
      python: "3.6"
services: postgresql
env: DATABASE_URL="postgres://postgres@localhost/dmp"
install: pip install -r requirements.txt coverage coveralls
script: coverage run --source='music_publisher' manage.py test
after_success: coveralls

